/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU */

#ifndef _Included_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
#define _Included_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID
#define net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID 3270366292953409655LL
#undef net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID
#define net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID 3613350191235561000LL
#undef net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID
#define net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_serialVersionUID 3613350191235561000LL
/*
 * Class:     net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
 * Method:    allocateMemoryGPU
 * Signature: (IIIILnet/sf/jclec/problem/classification/evolutionarylearner/RuleEvaluatorGPU;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_allocateMemoryGPU
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
 * Method:    copyDatasetGPU
 * Signature: (ILnet/sf/jclec/problem/classification/evolutionarylearner/RuleEvaluatorGPU;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_copyDatasetGPU
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
 * Method:    evaluateGPU
 * Signature: (ILnet/sf/jclec/problem/classification/evolutionarylearner/RuleEvaluatorGPU;)V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_evaluateGPU
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU
 * Method:    releaseGPU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jclec_problem_classification_evolutionarylearner_RuleEvaluatorGPU_releaseGPU
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
